import Cake from "../assets/Home/Rectangle 291.png";
import Cake2 from "../assets/Home/Rectangle 18.png";
import Cake3 from "../assets/Home/Rectangle 293.png";
import Cake4 from "../assets/Home/Rectangle 295.png";
import Cake5 from "../assets/Home/Rectangle 299.png";
const data = [
  {
    id: 1,
    name: "كوكي كيك مزينة بالورود",
    image: Cake,
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 2,
    image: Cake2,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 3,
    image: Cake3,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 4,
    image: Cake4,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 5,
    image: Cake4,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 6,
    image: Cake,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 7,
    image: Cake2,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 8,
    image: Cake3,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 9,
    image: Cake4,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 10,
    image: Cake5,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 12,
    image: Cake,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 12,
    image: Cake2,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 13,
    image: Cake3,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 14,
    image: Cake4,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 15,
    image: Cake5,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  //
  {
    id: 16,
    image: Cake,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 17,
    image: Cake2,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 18,
    image: Cake3,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 19,
    image: Cake4,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 20,
    image: Cake5,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  //
  {
    id: 21,
    image: Cake,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 22,
    image: Cake2,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 23,
    image: Cake3,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 24,
    image: Cake4,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
  {
    id: 25,
    image: Cake5,
    name: "كوكي كيك مزينة بالورود",
    price: 100,
    quantity: 0,
    avalible: 100,
  },
];
export { data };
